# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190101_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decide',
            name='cid',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='decide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='decide',
            name='sid',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='decide',
            name='sname',
            field=models.CharField(max_length=64),
        ),
    ]
