# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190101_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decide',
            old_name='sid',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='decide',
            old_name='sname',
            new_name='aname',
        ),
    ]
