# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20190101_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(db_column='状态', default='待审核', max_length=32),
        ),
    ]
