# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(db_column='活动时间'),
        ),
    ]
