# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20190102_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cname',
            field=models.CharField(db_column='社团', max_length=64),
        ),
    ]
