# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-03 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20190102_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='join',
            name='sid',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
