# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(db_column='活动名称', max_length=64)),
                ('cname', models.CharField(db_column='社团', max_length=64)),
                ('date', models.DateTimeField(db_column='活动时间')),
            ],
        ),
    ]
